[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - 35581 - LOGS_CAPTURED - Started capturing logs in process (pid: 35581).
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - 35581 - spark_operator.merge_and_analyze - STEP_RESTARTED - Started re-execution (attempt # 2) of step "spark_operator.merge_and_analyze".
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_A]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AA]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AABB]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AABVF]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AACAF]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AACI]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AACS]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AACT]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AACTF]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - spark_operator.merge_and_analyze - No previously stored outputs found for source StepOutputHandle(step_key='spark_operator.create_stock_tables[stock_AADI]', output_name='metric_and_series', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - 35581 - spark_operator.merge_and_analyze - STEP_INPUT - Got input "df_list" of type "Any". (Type check passed).
[32m2024-05-24 23:11:47 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0545f21f-f032-4224-bec8-186244e227f0 - 35581 - spark_operator.merge_and_analyze - STEP_UP_FOR_RETRY - Execution of step "spark_operator.merge_and_analyze" failed and has requested a retry in 0.4083595395140066 seconds.

dagster._core.execution.plan.utils.RetryRequestedFromPolicy

Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 525, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 203, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 100, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 208, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 177, in _yield_compute_results
    for event in iterate_with_context(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 466, in iterate_with_context
    with context_fn():
  File "/home/gitpod/.pyenv/versions/3.12.3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 72, in op_execution_error_boundary
    raise RetryRequestedFromPolicy(

The above exception was caused by the following exception:
KeyError: 'mtrc'

Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/practical-data-engineering/finnhub-batch-stock-pipeline/finnhub_batch_stock_pipeline/assets/spark_transformations.py", line 344, in merge_and_analyze
    schema = schemas['mtrc'])
             ~~~~~~~^^^^^^^^

