[32m2024-05-23 12:08:22 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - 219117 - LOGS_CAPTURED - Started capturing logs in process (pid: 219117).
[32m2024-05-23 12:08:22 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - 219117 - dimension_tables - STEP_START - Started execution of step "dimension_tables".
[32m2024-05-23 12:08:22 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - dimension_tables - Loading S3 object from: s3a://dagster-api/staging/2024-05-23/metric
[32m2024-05-23 12:08:27 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - 219117 - dimension_tables - LOADED_INPUT - Loaded input "metric" using input manager "s3_prqt_io_manager", from output "metric" of step "spark_operator.merge_and_analyze"
[32m2024-05-23 12:08:27 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - dimension_tables - Loading S3 object from: s3a://dagster-api/staging/2024-05-23/series
[32m2024-05-23 12:08:27 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - 219117 - dimension_tables - LOADED_INPUT - Loaded input "series" using input manager "s3_prqt_io_manager", from output "series" of step "spark_operator.merge_and_analyze"
[32m2024-05-23 12:08:27 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - 219117 - dimension_tables - STEP_INPUT - Got input "metric" of type "Any". (Type check passed).
[32m2024-05-23 12:08:27 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - 219117 - dimension_tables - STEP_INPUT - Got input "series" of type "Any". (Type check passed).
[32m2024-05-23 12:08:36 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - 219117 - dimension_tables - STEP_OUTPUT - Yielded output "metric_dim" of type "Table". (Type check passed).
[32m2024-05-23 12:08:36 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - dimension_tables - IO manager mode overridden with the asset metadata mode, overwrite -> append
[32m2024-05-23 12:08:36 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - dimension_tables - Writing with mode: append
[32m2024-05-23 12:08:36 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 2e0f248d-2030-41aa-831a-66d1973b9e5b - 219117 - dimension_tables - STEP_FAILURE - Execution of step "dimension_tables" failed.

dagster._core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "metric_dim" of step "dimension_tables"::

OSError: Generic S3 error: Error after 0 retries in 9.58Âµs, max_retries:10, retry_timeout:180s, source:builder error for url (http://127.0.0.1:9000/dagster-api/core/metric_dim/_delta_log/_last_checkpoint): URL scheme is not allowed

Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 800, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/storage/db_io_manager.py", line 147, in handle_output
    handler_metadata = self._handlers_by_type[obj_type].handle_output(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster_deltalake/handler.py", line 95, in handle_output
    write_deltalake(  # type: ignore
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/deltalake/writer.py", line 251, in write_deltalake
    table, table_uri = try_get_table_and_table_uri(table_or_uri, storage_options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/deltalake/writer.py", line 622, in try_get_table_and_table_uri
    table = try_get_deltatable(table_or_uri, storage_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/deltalake/writer.py", line 635, in try_get_deltatable
    return DeltaTable(table_uri, storage_options=storage_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/deltalake/table.py", line 401, in __init__
    self._table = RawDeltaTable(
                  ^^^^^^^^^^^^^^
[0m
