[32m2024-05-24 23:16:32 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - 51281 - LOGS_CAPTURED - Started capturing logs in process (pid: 51281).
[32m2024-05-24 23:16:32 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - 51281 - spark_operator.create_stock_tables[stock_AABB] - STEP_START - Started execution of step "spark_operator.create_stock_tables[stock_AABB]".
[32m2024-05-24 23:16:32 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - spark_operator.create_stock_tables[stock_AABB] - Loading file from: /workspace/practical-data-engineering/finnhub-batch-stock-pipeline/home/storage/c82b3d51-c538-413c-8b24-009f0a3066fe/spark_operator.stock_tables/result/stock_AABB using PickledObjectFilesystemIOManager...
[32m2024-05-24 23:16:32 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - 51281 - spark_operator.create_stock_tables[stock_AABB] - LOADED_INPUT - Loaded input "input_fn" using input manager "io_manager", from output "result" of step "spark_operator.stock_tables"
[32m2024-05-24 23:16:32 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - 51281 - spark_operator.create_stock_tables[stock_AABB] - STEP_INPUT - Got input "input_fn" of type "Any". (Type check passed).
[32m2024-05-24 23:18:00 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - spark_operator.create_stock_tables[stock_AABB] - Row(10DayAverageTradingVolume=5.72768, 13WeekPriceReturnDaily=-31.9703, 26WeekPriceReturnDaily=-6.1538, 3MonthADReturnStd=78.17949, 3MonthAverageTradingVolume=7.4307, 52WeekHigh=0.0418, 52WeekHighDate='2023-05-24', 52WeekLow=0.0114, 52WeekLowDate='2023-10-16', 52WeekPriceReturnDaily=-52.9563, 5DayPriceReturnDaily=-4.1885, beta=-1.07874, monthToDatePriceReturnDaily=-18.6667, priceRelativeToS&P50013Week=-38.5309, priceRelativeToS&P50026Week=-23.9776, priceRelativeToS&P5004Week=-30.8413, priceRelativeToS&P50052Week=-80.9067, priceRelativeToS&P500Ytd=-18.577, yearToDatePriceReturnDaily=-7.1066)
[32m2024-05-24 23:18:27 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - 51281 - spark_operator.create_stock_tables[stock_AABB] - STEP_OUTPUT - Yielded output "metric_and_series" of type "Any". (Type check passed).
[32m2024-05-24 23:18:30 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - spark_operator.create_stock_tables[stock_AABB] - Writing S3 object at: s3a://dagster-api/staging/2024-05-24/spark_operator.create_stock_tables[stock_AABB]/metric_and_series
[32m2024-05-24 23:18:30 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - spark_operator.create_stock_tables[stock_AABB] - Removing existing S3 object: staging/2024-05-24/spark_operator.create_stock_tables[stock_AABB]/metric_and_series
[32m2024-05-24 23:18:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - c82b3d51-c538-413c-8b24-009f0a3066fe - 51281 - spark_operator.create_stock_tables[stock_AABB] - STEP_UP_FOR_RETRY - Execution of step "spark_operator.create_stock_tables[stock_AABB]" failed and has requested a retry in 0.19654757831658137 seconds.

dagster._core.execution.plan.utils.RetryRequestedFromPolicy

Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 532, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 587, in _type_check_and_store_output
    for evt in _store_output(step_context, step_output_handle, output):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 810, in _store_output
    for elt in iterate_with_context(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 466, in iterate_with_context
    with context_fn():
  File "/home/gitpod/.pyenv/versions/3.12.3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 72, in op_execution_error_boundary
    raise RetryRequestedFromPolicy(

The above exception was caused by the following exception:
py4j.protocol.Py4JJavaError: An error occurred while calling o122.save.
: java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2625)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2590)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.delta.DeltaLog$.apply(DeltaLog.scala:767)
	at org.apache.spark.sql.delta.DeltaLog$.forTable(DeltaLog.scala:677)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:189)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:859)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:304)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:240)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentialsProvider
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 56 more


Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 800, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/practical-data-engineering/finnhub-batch-stock-pipeline/finnhub_batch_stock_pipeline/iomanagers/staging_s3_parquet_io_manager.py", line 150, in handle_output
    return self.inner_io_manager().handle_output(context, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/storage/upath_io_manager.py", line 446, in handle_output
    self.dump_to_path(context=context, obj=obj, path=path)
  File "/workspace/practical-data-engineering/finnhub-batch-stock-pipeline/finnhub_batch_stock_pipeline/iomanagers/staging_s3_parquet_io_manager.py", line 82, in dump_to_path
    obj.write.format("delta").mode('overwrite').save(pathe)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 1463, in save
    self._jwrite.save(path)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
    return f(*a, **kw)
           ^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(

