[32m2024-05-23 03:13:06 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - 533550 - LOGS_CAPTURED - Started capturing logs in process (pid: 533550).
[32m2024-05-23 03:13:06 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - 533550 - spark_operator.create_stock_tables[stock_AABB] - STEP_RESTARTED - Started re-execution (attempt # 2) of step "spark_operator.create_stock_tables[stock_AABB]".
[32m2024-05-23 03:13:06 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - spark_operator.create_stock_tables[stock_AABB] - Loading file from: /workspace/practical-data-engineering/finnhub-batch-stock-pipeline/home/storage/029b69ed-c8ff-498b-b60c-60c29c9a42bf/spark_operator.stock_tables/result/stock_AABB using PickledObjectFilesystemIOManager...
[32m2024-05-23 03:13:06 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - 533550 - spark_operator.create_stock_tables[stock_AABB] - LOADED_INPUT - Loaded input "input_fn" using input manager "io_manager", from output "result" of step "spark_operator.stock_tables"
[32m2024-05-23 03:13:06 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - 533550 - spark_operator.create_stock_tables[stock_AABB] - STEP_INPUT - Got input "input_fn" of type "Any". (Type check passed).
[32m2024-05-23 03:13:24 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - spark_operator.create_stock_tables[stock_AABB] - Row(10DayAverageTradingVolume=5.4521, 13WeekPriceReturnDaily=-30.3371, 26WeekPriceReturnDaily=-7, 3MonthADReturnStd=97.2845, 3MonthAverageTradingVolume=7.4821, 52WeekHigh=0.0418, 52WeekHighDate='2023-05-24', 52WeekLow=0.0114, 52WeekLowDate='2023-10-16', 52WeekPriceReturnDaily=-43.2927, 5DayPriceReturnDaily=-2.1053, beta=-1.07874, monthToDatePriceReturnDaily=-17.3333, priceRelativeToS&P50013Week=-37.3022, priceRelativeToS&P50026Week=-25.4142, priceRelativeToS&P5004Week=-29.8308, priceRelativeToS&P50052Week=-70.1725, priceRelativeToS&P500Ytd=-17.3761, yearToDatePriceReturnDaily=-5.5838)
[32m2024-05-23 03:13:29 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - 533550 - spark_operator.create_stock_tables[stock_AABB] - STEP_OUTPUT - Yielded output "metric_and_series" of type "Any". (Type check passed).
[32m2024-05-23 03:13:29 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - spark_operator.create_stock_tables[stock_AABB] - Writing S3 object at: s3a://dagster-api/staging/2024-05-23/spark_operator.create_stock_tables[stock_AABB]/metric_and_series
[32m2024-05-23 03:13:29 +0000[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - spark_operator.create_stock_tables[stock_AABB] - Removing existing S3 object: staging/2024-05-23/spark_operator.create_stock_tables[stock_AABB]/metric_and_series
[32m2024-05-23 03:30:32 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 029b69ed-c8ff-498b-b60c-60c29c9a42bf - 533550 - spark_operator.create_stock_tables[stock_AABB] - STEP_UP_FOR_RETRY - Execution of step "spark_operator.create_stock_tables[stock_AABB]" failed and has requested a retry in 0.4442683501316839 seconds.

dagster._core.definitions.events.RetryRequested

Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 532, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 587, in _type_check_and_store_output
    for evt in _store_output(step_context, step_output_handle, output):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 810, in _store_output
    for elt in iterate_with_context(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 466, in iterate_with_context
    with context_fn():
  File "/home/gitpod/.pyenv/versions/3.12.3/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 94, in op_execution_error_boundary
    raise RetryRequested(

The above exception was caused by the following exception:
dagster._core.errors.DagsterExecutionInterruptedError

Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 800, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/practical-data-engineering/finnhub-batch-stock-pipeline/finnhub_batch_stock_pipeline/iomanagers/staging_s3_parquet_io_manager.py", line 150, in handle_output
    return self.inner_io_manager().handle_output(context, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_core/storage/upath_io_manager.py", line 446, in handle_output
    self.dump_to_path(context=context, obj=obj, path=path)
  File "/workspace/practical-data-engineering/finnhub-batch-stock-pipeline/finnhub_batch_stock_pipeline/iomanagers/staging_s3_parquet_io_manager.py", line 82, in dump_to_path
    obj.write.format("delta").mode('overwrite').save(pathe)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 1463, in save
    self._jwrite.save(path)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/py4j/java_gateway.py", line 1321, in __call__
    answer = self.gateway_client.send_command(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.12.3/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dagster/_utils/interrupts.py", line 82, in _new_signal_handler
    raise error_cls()

